@baseURL = http://localhost:5500
@urlPath = api/v1

###
POST {{baseURL}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "safal",
  "password": "safal",
  "email": "safal@gmail.com",
  "avatarColor": "#fffff",
  "avatarImage": "safda"
}
