@baseUrl = http://localhost:5500
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/65df6f93fa8767acd22030a0
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/<postId>/<commentId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "postId": "65df6f93fa8767acd22030a0",
  "comment": "I like this post. Thumbs Up"
}
