@baseUrl = http://localhost:5500
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/notification/65e35b5b78b73851a0619522
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
DELETE {{baseUrl}}/{{urlPath}}/notification/<notificationId>
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
