@baseUrl = http://localhost:5500
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/all/1
# GET {{baseUrl}}/{{urlPath}}/post/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/images/1
# GET {{baseUrl}}/{{urlPath}}/post/images/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

# Privacy - Public | Private | Followers
# Feelings - like | love | wow | happy | sad | angry

{
  "post": "I am also here in wandroz",
  "privacy": "Public",
  "feelings": "",
  "gifUrl": ""
}

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "I welcome myself to wandroz",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "feelings": "",
  "images": [""]
}

###
PUT {{baseUrl}}/{{urlPath}}/post/65e4475625ee51d75cccfae6
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "Hello test this images please",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "feelings": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/post/image/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "feelings": "",
  "imgId": "<imgId-form-post>",
  "imgVersion": "<imgVersion-for-post>",
  "image": "<base64-encoded-string>"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true
